package com.Clover.springboot.Model;
// default package
// Generated 23 Mar, 2020 2:40:52 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tasks generated by hbm2java
 */
@Entity
@Table(name = "tasks", catalog = "sys")
public class Tasks implements java.io.Serializable {

	private Integer taskId;
	private String title;
	private byte status;
	private byte priority;
	private String description;

	public Tasks() {
	}

	public Tasks(String title, byte status, byte priority) {
		this.title = title;
		this.status = status;
		this.priority = priority;
	}

	public Tasks(String title, byte status, byte priority, String description) {
		this.title = title;
		this.status = status;
		this.priority = priority;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "task_id", unique = true, nullable = false)
	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "priority", nullable = false)
	public byte getPriority() {
		return this.priority;
	}

	public void setPriority(byte priority) {
		this.priority = priority;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
